version: '2.1'
networks:
  ace:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
services:
  ace-rabbitmq:
    image: specterops/ace-rabbitmq
    container_name: ace-rabbitmq
    env_file: ./ace.env
    hostname: ace-rabbitmq
    networks:
      ace:
        ipv4_address: 172.19.0.2
        aliases:
          - rabbitmq.ace.local
    ports: 
      - 5672:5672
      - 15672:15672
  ace-sql:
    image: specterops/ace-sql
    container_name: ace-sql
    env_file: ./ace.env
    hostname: ace-sql
    networks:
      ace:
        aliases:
          - sql.ace.local
        ipv4_address: 172.19.0.3
    ports: 
      - 1433:1433
  ace-nginx:
    image: specterops/ace-nginx
    container_name: ace-nginx
    env_file: ./ace.env
    hostname: ace-nginx
    networks:
      ace:
        aliases:
          - nginx.ace.local
        ipv4_address: 172.19.0.4
    ports:
      - "80:80"
      - "443:443"
